// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXl_8AA_RyN06ucyARWk15VMVBseESMLg',
    appId: '1:552537737977:web:1234567890abcdef0d3028',
    messagingSenderId: '552537737977',
    projectId: 'pokeshop-app-e167d',
    authDomain: 'pokeshop-app-e167d.firebaseapp.com',
    storageBucket: 'pokeshop-app-e167d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXl_8AA_RyN06ucyARWk15VMVBseESMLg',
    appId: '1:552537737977:android:f085735c1b9db94e0d3028',
    messagingSenderId: '552537737977',
    projectId: 'pokeshop-app-e167d',
    storageBucket: 'pokeshop-app-e167d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXl_8AA_RyN06ucyARWk15VMVBseESMLg',
    appId: '1:552537737977:ios:1234567890abcdef0d3028',
    messagingSenderId: '552537737977',
    projectId: 'pokeshop-app-e167d',
    storageBucket: 'pokeshop-app-e167d.firebasestorage.app',
    iosBundleId: 'com.example.fluterNumiiiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXl_8AA_RyN06ucyARWk15VMVBseESMLg',
    appId: '1:552537737977:macos:1234567890abcdef0d3028',
    messagingSenderId: '552537737977',
    projectId: 'pokeshop-app-e167d',
    storageBucket: 'pokeshop-app-e167d.firebasestorage.app',
    iosBundleId: 'com.example.fluterNumiiiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXl_8AA_RyN06ucyARWk15VMVBseESMLg',
    appId: '1:552537737977:windows:1234567890abcdef0d3028',
    messagingSenderId: '552537737977',
    projectId: 'pokeshop-app-e167d',
    authDomain: 'pokeshop-app-e167d.firebaseapp.com',
    storageBucket: 'pokeshop-app-e167d.firebasestorage.app',
  );
}
